### PR TITLE
Simplify and speed-up download imagery command, add bbox parameter to…

### PR DESCRIPTION
**Pull request by m-mohr**
Implements parts of #29 (task 1 and 4 - potentially also 2, but don't have any good data for tests right now)

- simplify and speed-up inference download command (e.g. by not saving temporary files), not a big saving but a couple of seconds.
- add bbox parameter to reduce data transfer
- add progress bar for download

Example: `ftw inference download --win_a S2B_MSIL2A_20210617T100559_R022_T33UUP_20210624T063729 --win_b S2B_MSIL2A_20210925T101019_R022_T33UUP_20210926T121923 --out inference_imagery/austria_example.tif -f --bbox=13.0,48.0,13.1,48.1`

Just checked the output files from the old and new code and they seem to be identical.

### CODE REVIEW

**Comment by cholmes** [comment]
I got a weird error where if I did an `--out output.tif` it'd make an error (pasted below). But if I did `--out dir/output.tif` then it'd work fine. Seems like it expects a directory and fails if it's not one (this error may well have been there for awhile...)

```
File "/Users/cholmes/miniforge3/envs/ftw-c2/bin/ftw", line 8, in <module>
    sys.exit(ftw())
             ^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/miniforge3/envs/ftw-c2/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/cholmes/repos/ftw-baselines/src/ftw_cli/cli.py", line 93, in inference_download
    create_input(win_a, win_b, out, overwrite, bbox)
  File "/Users/cholmes/repos/ftw-baselines/src/ftw_cli/download_img.py", line 36, in create_input
    os.makedirs(os.path.dirname(out), exist_ok=True)
  File "<frozen os>", line 225, in makedirs
FileNotFoundError: [Errno 2] No such file or directory: ''
```

**Comment by m-mohr** [comment]
Yes, that issue did exist throughout some of the commands. I had fixed in in another place recently and fixed it also here now.

**Comment by cholmes** [comment]
Ok, got things working with a smaller patch size (256) (from conversations on slack). But when polygonizing I got `WARNING: Unable to parse timestamp from TIFFTAG_DATETIME tag.`

It looks like there is something there, not sure if the format changed:

```
Metadata:
  TIFFTAG_DATETIME=2021:09:25 10:10:19
```

The output of the three class model looks different - it's just black/white vs the red & green. I'll try to dig more into it (am on a different computer, so not sure if something else changed).

@m-mohr - could we use the 'default' thing in the CLI like we did with polygonize, to show what the default values are for patch_size, probably also batch_size, padding, resize_factor. And perhaps also tweak the defaults, like patch_size to 512, and resize_factor to 2 and maybe gpu 0 (since those seem to be used by default in the current flow). @calebrob6 - any thoughts on the right defaults here? 

Also we should update the readme. I can do it if you'd like. Mostly just run `ftw inference run` and put in the output, and then there's a couple other things that need little tweaks with the new functionality.

**Comment by m-mohr** [comment]
> But when polygonizing I got `WARNING: Unable to parse timestamp from TIFFTAG_DATETIME tag.`


> The output of the three class model looks different - it's just black/white vs the red & green. I'll try to dig more into it (am on a different computer, so not sure if something else changed).

Not sure I understand. Examples?

> @m-mohr - could we use the 'default' thing in the CLI like we did with polygonize

Yes, done.

> And perhaps also tweak the defaults

It determines a better patch size now, but I think gpu default is good as is. CPU is fail-safe, we don't know about the availability of a GPU (e.g. in CI)

> Also we should update the readme. I can do it if you'd like. Mostly just run `ftw inference run` and put in the output

Done.

> then there's a couple other things that need little tweaks with the new functionality.

Maybe you do that part? I'm not sure I'm aware of all the small tweaks you are envisioning ;-)

**Comment by cholmes** [comment]
> Not sure I understand. Examples?

This is what my output looks like for the three class:
Screenshot 2024-11-05 at 1 57 31 PM

I did just try to run on 'main' and got the same result, so there's some chance it's a bit of weirdness with the computer I'm on? I don't have the normal output right now, but usually it's red fields, like in https://github.com/fieldsoftheworld/ftw-baselines/blob/main/assets/austria_prediction.png

> Maybe you do that part? I'm not sure I'm aware of all the small tweaks you are envisioning ;-)
Sure, they're minor, will try to do them right now. Ok if I just commit directly to your branch?

**Comment by m-mohr** [comment]
@cholmes 

> This is what my output looks like for the three class

Yeah, it was always black for me. Never had red before. Not sure what to do here...

> Sure, they're minor, will try to do them right now. Ok if I just commit directly to your branch?

Yes, just make sure to pull once more because I just committed README updates.

**Comment by cholmes** [comment]
> Yes, just make sure to pull once more because I just committed README updates.

I did - was writing a comment about how I didn't see your readme updates when the update came in.

> Hmm, it was always black for me. Never had red before. Not sure what to do here...
Is that not just a styling thing in QGIS?

I'm pretty sure previous ones had a built in color map that by default got rendered in QGIS. But sounds like it's not a problem with this particular set of work - for some reason it only first popped up for me when looking at this PR, but my sanity check to try it with main resulted in the same, so it seems like it wasn't introduced here, which was my worry. I say we merge this in, and I can continue to look at this tonight, when I'm back at my computer.

**Comment by m-mohr** [comment]
Oh, that was likely because we write the files directly from ODC / rioxarray now instead of through rasterio.
The old code passed through some additional details from the source COG, which is not the case anymore.
Not sure whether we loose anything important now?

**Comment by cholmes** [comment]
> Oh, that might be because we write the files directly from ODC / rioxarray now instead of through rasterio. I can't pass through the source image COG profile now. The old code passed through some additional options from the source COG, which is not the case anymore. This may include the color map.

It seems weird to me the color map would come from the source COG... But I do remember there most always being a color map.

> A little confusing though that it's not happening on main. Maybe I'm wrong ;-)

Yeah, I'll try to do more testing and confirm later, I may have not built main quite right or something.

I just ran through everything else though (download -> run -> polygonize) and it all worked great. Nice work on this!

**Comment by cholmes** [comment]
Oh, we should update the example download in the readme so it uses the smaller area, so the experience goes much faster.

**Comment by cholmes** [comment]
Ok, inference on full scenes is very slow on my computer and I've not managed to test much. But here is a comparison of inference output a couple weeks ago vs. today:

inference-output

These are both 3 class outputs. The one today only seems to have 2 values.

**Comment by calebrob6** [comment]
It looks like:
```
f.write_colormap(1, {1: (255, 0, 0), 2:(0, 255, 0)})
f.colorinterp = [ColorInterp.palette]
```

were removed when writing the output raster at some point (these write a color palette to the tiff).

**Comment by cholmes** [comment]
Just tested end-to-end and it all works great! Merge it! Thanks for all your great work on this, the process to download, run and polygonize took under a minute :)

**Pull request merged**
